services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MySqlConnection=Server=db;Port=3306;Database=paynaudb;User=root;Password=Clinshesh32*;
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Clinshesh32*
      MYSQL_DATABASE: paynaudb
    volumes:
      - db_data:/var/lib/mysql

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

volumes:
  db_data: {}
